name: twitch_affiliate_tracker
description: A Twitch growth tracking app.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_messaging: ^15.2.1
  firebase_dynamic_links: ^6.1.1
  firebase_analytics: ^11.4.1
  flutter_local_notifications: ^18.0.1
  flutter_dotenv: ^5.0.2
  google_mobile_ads: 5.3.1
  in_app_update: ^4.2.3
  shared_preferences: ^2.2.2
  in_app_purchase: ^3.1.9
  intl: ^0.20.2
  provider: ^6.1.2
  http: ^1.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
