name: twitchaffiliatetracker
version: 1.0.0+1
description: A Twitch growth tracking app.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0  # Updated for compatibility
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_messaging: ^15.2.1
  firebase_analytics: ^11.4.1
  flutter_local_notifications: ^18.0.1
  flutter_dotenv: ^5.2.1
  in_app_update: ^4.2.3
  shared_preferences: ^2.2.2
  in_app_purchase: ^3.1.9
  intl: ^0.20.2
  provider: ^6.1.2
  http: ^1.2.0
  url_launcher: ^6.3.1
  twitch_api: ^0.7.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/.env
